accounts/urls.py
from accounts.views import Index, RegisterDoctor, RegisterPatient
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("register/doctor", RegisterDoctor.as_view(), name='register-doctor'),
    path("register/patient", RegisterPatient.as_view(), name='register-patient'),
    path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", logout_then_login, name="logout"),
]

blog/urls.py
from blog.views import CreatePost, ListPost, MyList, Publish, PostDetail
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path("post/create/", CreatePost.as_view(), name='create-post'),
    path("post/all/", ListPost.as_view(), name='post-list'),
    path("post/my/", MyList.as_view(), name="my-post"),
    path("post/publish/", Publish.as_view(), name="publish-post"),
    path("post/<int:id>/", PostDetail.as_view(), name="post-detail"),
]

task1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from localflavor.in_.models import INStateField

class CustomUser(AbstractUser):
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    profile_pic = models.ImageField(verbose_name=("Profile Picture"), default="default.jpg", upload_to='profile_pics')
    address1 = models.CharField(verbose_name=("Address line 1"), max_length=1000, blank=True, null=True)
    city = models.CharField(verbose_name=("City"), max_length=255, blank=True, null=True)
    state = INStateField(blank=True, null=True)
    pincode = models.CharField(max_length=6, blank=True, null=True)
    REQUIRED_FIELDS = ['first_name', 'profile_pic']
    

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

user = get_user_model()

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    summary = models.CharField(max_length=255)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(user, on_delete=models.CASCADE)

accounts/forms.py
from accounts.models import CustomUser
from django.contrib.auth.forms import UserCreationForm
class CreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'profile_pic', 'username', 'email', 'password1', 'password2', 'address1', 'city', 'state', 'pincode', 'is_patient', 'is_doctor')

blog/forms.py
from django import forms 
from blog.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'category', 'summary', 'content', 'draft']
        widgets = {
            'title': forms.TextInput(attrs={"placeholder": "Title", "autofocus": "autofocus"}),
            'summary': forms.TextInput(attrs={"placeholder": "Summary"}),
            'content': forms.Textarea(attrs={"placeholder": "Content", "rows": "4"}),
        }

accounts/views.py
from accounts.models import CustomUser
from accounts.forms import CreationForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from localflavor.in_.in_states import STATE_CHOICES

class RegisterDoctor(CreateView):
    form_class = CreationForm
    model = CustomUser
    template_name = "accounts/register_doctor.html"
    success_url = reverse_lazy("accounts:login")

class RegisterPatient(CreateView):
    form_class = CreationForm
    model = CustomUser
    template_name = "accounts/register_patient.html"
    success_url = reverse_lazy("accounts:login")

class Index(LoginRequiredMixin, View):
    login_url = reverse_lazy("accounts:login")

    def get(self, request):
        context = {
            "user":request.user,
            "state": dict(STATE_CHOICES).get(request.user.state, None),
        }
        return render(request, "accounts/index.html", context)

blog/views.py
from blog.forms import PostForm
from blog.models import Post, Category
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView
# Create your views here.

class CreatePost(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = "blog/create_post.html"
    success_url = reverse_lazy("accounts:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self) -> str:
        if self.object.draft == True:
            messages.success(self.request, "Post Saved as Draft!")
        else:
            messages.success(self.request, "Post Published Successfully!")
        return super().get_success_url()

    def test_func(self):
        return self.request.user.is_doctor == True

class ListPost(LoginRequiredMixin, ListView):
    model = Post
    template_name = "blog/post_list.html"

    def get_context_data(self, **kwargs):
        context = dict()
        categories = Category.objects.all()
        context["items"] = dict()
        for category in categories:
            lst = category.category.filter(draft=False)
            if len(lst) != 0:
                context["items"][category] = lst
        return context

class MyList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self):
        return self.request.user.is_doctor == True
    model = Post
    template_name = "blog/doctor_post.html"

    def get_context_data(self, **kwargs):
        context = dict()
        context["post_list"] = Post.objects.filter(author=self.request.user)
        return context

class Publish(LoginRequiredMixin, UserPassesTestMixin, View):
    def post(self, request):
        id = int(request.POST.get("id"))
        post = Post.objects.get(id=id)
        if post.author != request.user:
            return redirect(reverse_lazy("accounts:index"))
        post.draft = False
        post.save()
        messages.success(request, "Post Published Successfully!")
        return redirect(reverse_lazy("blog:my-post"))

    def test_func(self):
        return self.request.user.is_doctor == True

class PostDetail(LoginRequiredMixin, View):
    def get(self, request, id):
        post = get_object_or_404(Post, id=id)

        if post.draft == True and post.author != request.user:
            return redirect(reverse_lazy("blog:post-list"))
        context = {
            "post": post,
        }
        return render(request, "blog/post_detail.html", context)

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}
Index
{% endblock title %}

{% block main %}
<section style="background-color: #eee;" class="m-5">
    <h3 class="text-center m-4">
        {% if user.is_patient %}
        Patient Details 
        {% endif %}
        {% if user.is_doctor %}
        Doctor Detail
        {% endif %}
    </h3>
      <div class="row  m-3">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="{{ user.profile_pic.url }}" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">
                {% if user.is_doctor %}Dr.{% endif %}
                {{ user.first_name|capfirst }} {{ user.last_name|capfirst }}
            </h5>
              <p class="text-muted mb-4">{{ user.city|capfirst }}, {{ user.state|capfirst }} - {{ user.pincode }}</p>
            
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"> 
                    {% if user.is_doctor %}Dr.{% endif %}
                    {{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ user.email }}</p>
                </div>
            </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Username</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ user.username }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ user.address1|capfirst }}, {{ user.city|capfirst }} - {{ user.pincode }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">State</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ state }}</p>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="text-center m-2">
        <a href="{% url 'accounts:logout' %}?next={% url 'accounts:login' %}" class="btn btn-danger text-center">Logout</a>
    </div>
</section>
{% endblock main %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block main %}
<div class="text-center">

    <h2 class="m-5">Login Page</h2>
    
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <input type="text" autofocus autocomplete="off" name="username">
        </div>
    <div class="mb-3">
        <input type="password" name="password">
    </div>
    {% for key, value in form.errors.items %}
    {{ value }}
    {% endfor %}
    <input type="hidden" name="next" value="{% url 'accounts:index' %}">
    <button class="btn btn-primary text-center"d E type="submit">Log In</button>
    <div class="text-center m-3">
        <p>Not a member? Register as <a href="{% url 'accounts:register-doctor' %}">Doctor</a> or <a href="{% url 'accounts:register-patient' %}">Patient</a></p>
      </div>
</form>
</div>
<script>
    inputs = document.getElementsByTagName("input");
    for (let i = 1; i < inputs.length; i++) {
        inputs[i].placeholder = inputs[i].name.charAt(0).toUpperCase() + inputs[i].name.substring(1);
        inputs[i].classList.add("form-control")
        inputs[i].classList.add("mx-auto")
        inputs[i].classList.add("w-auto")
    }
</script>
{% endblock main %}

accounts/templates/accounts/register_doctor.html
{% extends 'base.html' %}

{% block main %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form class="mx-1 mx-md-4" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.first_name }}
                        {{ form.errors.first_name }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.last_name }}
                        {{ form.errors.last_name }}
                      </div>
                    </div>
                    
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.profile_pic }}
                        {{ form.errors.profile_pic }}
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.username }}
                        {{ form.errors.username }}
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.email }}
                        {{ form.errors.email }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.password1 }}
                        {{ form.errors.password1 }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.password2 }}
                        {{ form.errors.password2 }}
                      </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.address1 }}
                            {{ form.errors.address1 }}
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.city }}
                            {{ form.errors.city }}
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.state }}
                            {{ form.errors.state }}
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.pincode }}
                            {{ form.errors.pincode }}
                        </div>
                    </div>
                    
                    <input type="hidden" name="is_doctor" value="1">
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit" class="btn btn-primary btn-lg" value="Register"></input>
                    </div>
                    <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{% url 'accounts:login' %}"
                        class="fw-bold text-body"><u>Login here</u></a></p>
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<script>
    let inputs = document.querySelectorAll('input');
    let select = document.querySelectorAll('select');
    select[0].classList.add("form-select");
    select[0].selectedIndex = 1;
    for (let i = 1; i < inputs.length; i++) {
        inputs[i].classList.add("form-control");
    } 
    inputs[1].placeholder = "First Name";
    inputs[2].placeholder = "Last Name";
    inputs[4].placeholder = "Username";
    inputs[5].placeholder = "Email";
    inputs[6].placeholder = "Password";
    inputs[7].placeholder = "Confirm Password";
    inputs[8].placeholder = "Address";
    inputs[9].placeholder = "City";
    inputs[10].placeholder = "Pincode";
    inputs[1].focus();

</script>
{% endblock main %}

accounts/templates/accounts/register_patient.html
{% extends 'base.html' %}

{% block main %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
  
                  <form class="mx-1 mx-md-4" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.first_name }}
                        {{ form.errors.first_name }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.last_name }}
                        {{ form.errors.last_name }}
                      </div>
                    </div>
                    
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.profile_pic }}
                        {{ form.errors.profile_pic }}
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.username }}
                        {{ form.errors.username }}
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.email }}
                        {{ form.errors.email }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.password1 }}
                        {{ form.errors.password1 }}
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        {{ form.password2 }}
                        {{ form.errors.password2 }}
                      </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.address1 }}
                            {{ form.errors.address1 }}
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.city }}
                            {{ form.errors.city }}
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.state }}
                            {{ form.errors.state }}
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                            {{ form.pincode }}
                            {{ form.errors.pincode }}
                        </div>
                    </div>
                    <input type="hidden" name="is_patient" value="1">
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit" class="btn btn-primary btn-lg" value="Register"></input>
                    </div>
                    <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{% url 'accounts:login' %}"
                        class="fw-bold text-body"><u>Login here</u></a></p>
                  </form>
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<script>
    let inputs = document.querySelectorAll('input');
    let select = document.querySelectorAll('select');
    select[0].classList.add("form-select");
    select[0].selectedIndex = 1;
    for (let i = 1; i < inputs.length; i++) {
        inputs[i].classList.add("form-control");
    } 
    inputs[1].placeholder = "First Name";
    inputs[2].placeholder = "Last Name";
    inputs[4].placeholder = "Username";
    inputs[5].placeholder = "Email";
    inputs[6].placeholder = "Password";
    inputs[7].placeholder = "Confirm Password";
    inputs[8].placeholder = "Address";
    inputs[9].placeholder = "City";
    inputs[10].placeholder = "Pincode";
    inputs[1].focus();

</script>
{% endblock main %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% load static %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <i class="fas fa-bars"></i>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:index' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post-list' %}">All Posts</a>
            </li>
            {% if user.is_doctor %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:my-post' %}">My Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:create-post' %}">Create Post</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>
{% endif %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} text-center" role="alert">
        {{ message }}
      </div>
    {% endfor %}
{% endif %}

    <div class="container-fluid">
        {% block main %}
        {% endblock main %}
    </div>
</body>
</html>

blog/templates/blog/doctor_post.html
{% extends 'base.html' %}

{% block title %}
My Posts
{% endblock title %}

{% block main %}
{% if post_list %}
<div class="container m-5">
    <div class="col-md-12 col-lg-12">
        {% for post in post_list %}
        <article class="post vt-post my-5">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
                    <div class="post-type post-img">
                        <a href="{% url 'blog:post-detail' post.id %}"><img src="{{ post.image.url }}" alt="image post"
                            class="img-fluid" style="width: 12rem;"></a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-8">
                    <div class="caption">
                        <h2 class="md-heading"><a href="{% url 'blog:post-detail' post.id %}">{{ post.title|capfirst }}</a></h2>
                        <p style="font-size:1.5rem;">{{ post.summary|truncatewords:15|capfirst }}</p>
                        <a class="" href="{% url 'blog:post-detail' post.id %}" role="button" style="font-size:1.5rem;">Read More</a> </div>
                    </div>
                    {% if post.draft %}
                    <div class="col-xs-12 col-sm-1 col-md-1 col-lg-1">
                        <form action="{% url 'blog:publish-post' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ post.id }}">
                            <button type="submit" class="btn btn-primary">Publish</button>
                        </form>
                    </div>
                    {% endif %}
                </div>
            </article>
            {% endfor %}  
        </div>
    </div>
    {% else %}
    <h2 class="text-center my-5">You Have Not Created Any Post. Please Create One!</h2>
    {% endif %}
{% endblock main %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block main %}
<div class="col-lg-12 post">
    <div class="container">

        <h2 class="ubuntu">{{ post.title|capfirst }}</h2>
        <div class="body-text">

            <p class='text-muted ubuntu'>By Dr. {{ post.author.first_name|capfirst }} {{ post.author.last_name|capfirst }}</p>
            <br>
            <div class="row">
                <div class="col-lg-6"><p class=""><img alt="image" src="{{ post.image.url }}" width="90%"></p></div>
            </div>
            <br/>
            <div class="row">
                
                    <p>{{ post.content|capfirst }}</p></div>
            </div>
            <br/>

            <p>Thanks!</p>
            <div class="row">
                <div class="col-lg-12 aboutme">
                    <div class="media">
                            <img class="media-object dp img-circle" src="{{ post.author.profile_pic.url }}" style="width: 120px;height:120px;">
                        <div class="media-body">
                            <h4 class="media-heading">Dr. {{ post.author.first_name|capfirst }} {{ post.author.last_name|capfirst }}</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock main %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block title %}
Post List
{% endblock title %}

{% block main %}

{% if items %}
<div class="container m-5">
    <div class="col-md-12 col-lg-12">
        {% for category, posts in items.items %}
        <h2>{{ category.name }}</h2>
        {% for post in posts %}
        <article class="post vt-post my-5">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
                    <div class="post-type post-img">
                        <a href="{% url 'blog:post-detail' post.id %}"><img src="{{ post.image.url }}" alt="image post"
                            class="img-fluid" style="width: 12rem;"></a>
                        </div>
                    </div>
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-8">
                    <div class="caption">
                        <h3 class="md-heading"><a href="{% url 'blog:post-detail' post.id %}">{{ post.title|capfirst }}</a></h3>
                        <p style="font-size:1.2rem;">-- By <strong> Dr. {{ post.author.first_name|capfirst }} {{ post.author.last_name|capfirst }} </strong> </p>
                        <p style="font-size:1.5rem;">{{ post.summary|truncatewords:15|capfirst }}</p>
                        <a class="" href="{% url 'blog:post-detail' post.id %}" role="button" style="font-size:1.5rem;">Read More</a> </div>
                </div>
            </div>
        </article>
        {% endfor %}        
        {% endfor %}        
    </div>
</div>
{% else %}
<h2 class="text-center m-5">No Post Available to Show!</h2>
{% endif %}

{% endblock main %}